Repository Sopan-Patil/PlatformTesting, pull requests merged in 2021-08, with the labels that each got.

#13 Sopan my page pt 45 49
  platform/src/main/java/platform/pageobjects/MyPage/AccountAndSecurity.java
  platform/src/test/java/platformfeatures/PF_AccountAndSecurity.feature
  platform/src/test/java/platformstepdefinition/PF_AccountAndSecurity.java
Labels: Code Review

#11 Cs account pt01 03
  Common/Common/src/main/java/utils/ExcelUtil.java
  Common/Common/src/main/java/utils/XLHandler.java
  platform/src/main/java/base/NewBaseClass.java
  platform/src/main/java/platform/pageobjects/AccountServices/CreateAccountStep1.java
  platform/src/main/java/platform/pageobjects/AccountServices/CreateAccountStep5.java
  platform/src/main/java/platform/pageobjects/Authentication/LoginPage.java
  platform/src/test/java/platformfeatures/PF_CreateAccount.feature
  platform/src/test/java/platformrunner/Runner.java
  platform/src/test/java/platformstepdefinition/PF_CreateAccount.java
Labels: Code Review

#14 Sopan my page pt 50 52
  Common/Common/src/main/java/utils/XLHandler.java
  platform/TestData/NewTestData.xlsx
  platform/src/main/java/platform/pageobjects/MyPage/AccountAndSecurity.java
  platform/src/main/java/platform/pageobjects/MyPage/MembershipStatus.java
  platform/src/test/java/platformfeatures/PF_MemberShipStatus.feature
  platform/src/test/java/platformrunner/Runner.java
  platform/src/test/java/platformstepdefinition/PF_MembershipStatus.java
Labels: Code Review

#8 Cs login pt12 pt14
  Common/Common/src/main/java/utils/XLHandler.java
  platform/src/main/java/base/NewBaseClass.java
  platform/src/main/java/platform/pageobjects/Authentication/LoginPage.java
  platform/src/test/java/platformfeatures/APF_Login.feature
  platform/src/test/java/platformrunner/Runner.java
  platform/src/test/java/platformstepdefinition/PF_Login.java
Labels: Code Review

#9 CS_PT34_PT35
  Common/Common/src/main/java/utils/XLHandler.java
  platform/src/main/java/base/NewBaseClass.java
  platform/src/main/java/platform/pageobjects/AccountServices/CreateAccountStep2.java
  platform/src/test/java/platformfeatures/PF_CreateAccount.feature
  platform/src/test/java/platformrunner/Runner.java
  platform/src/test/java/platformstepdefinition/PF_CreateAccount.java
Labels: Code Review

#15 Cs reset password pt16,pt18,pt19,pt22 pt29
  Common/Common/src/main/java/utils/ExcelUtil.java
  Common/Common/src/main/java/utils/XLHandler.java
  platform/TestData/NewTestData.xlsx
  platform/TestData/ValidationStrings.xlsx
  platform/src/main/java/base/NewBaseClass.java
  platform/src/main/java/platform/pageobjects/AccountServices/ResetPasswordStep1.java
  platform/src/main/java/platform/pageobjects/AccountServices/ResetPasswordStep3.java
  platform/src/main/java/platform/pageobjects/AccountServices/ResetPasswordStep4.java
  platform/src/main/java/platform/pageobjects/Authentication/ForgotPassword.java
  platform/src/test/java/platformfeatures/PF_Password.feature
  platform/src/test/java/platformrunner/Runner.java
  platform/src/test/java/platformstepdefinition/PF_Password.java
Labels: Code Review

#16 Rahul order pt62 pt89
  Common/Common/src/main/java/utils/CommonFunctions.java
  Common/Common/target/classes/utils/CommonFunctions.class
  platform/NewTestData.xlsx
  platform/resources/log4j2.xml
  platform/src/main/java/platform/pageobjects/Authentication/LoginPage.java
  platform/src/main/java/platform/pageobjects/Order/Order.java
  platform/src/test/java/platformfeatures/PF_Order.feature
  platform/src/test/java/platformrunner/Runner.java
  platform/src/test/java/platformstepdefinition/PF_Order.java
  platform/src/test/java/platformstepdefinition/PF_test.java
Labels: Requested Changes

#1 Header Menu and SubMenu Test 118 to 121
  platform/TestData/~$NewTestData.xlsx
  platform/src/main/java/platform/pageobjects/Header/Header.java
  platform/src/test/java/platformfeatures/PF_Header.feature
  platform/src/test/java/platformstepdefinition/PF_Header.java
Labels: Code Review

#18 Roopak Membership PT_53_54_55
  platform/src/main/java/platform/pageobjects/MyPage/Membership.java
  platform/src/test/java/platformfeatures/PF_Membership.feature
  platform/src/test/java/platformstepdefinition/PF_Membership.java
Labels: Requested Changes

#3 Sahaj footer pt 90-106
  .project
  platform/src/main/java/platform/pageobjects/Footer/FooterPage_PT90_106.java
  platform/src/main/java/platform/pageobjects/Footer/TermsConditionsFooter.java
  platform/src/test/java/platformfeatures/PF_Footer.feature
  platform/src/test/java/platformstepdefinition/PF_Footer.java
Labels: Approved

#20 remove string hardcoded, feature file and product list dynamic xpath is pending
  Common/Common/src/main/java/utils/ExcelUtil.java
  platform/src/main/java/platform/pageobjects/Order/Order.java
  platform/src/test/java/platformfeatures/PF_Order.feature
  platform/src/test/java/platformrunner/Runner.java
  platform/src/test/java/platformstepdefinition/PF_Order.java
  platform/src/test/java/platformstepdefinition/PF_test.java
Labels: Approved

#28 Amogh_header_pt_125
  platform/src/main/java/platform/pageobjects/Header/HeaderAfterLogin.java
  platform/src/test/java/platformfeatures/PF_HeaderAfterLogin.feature
  platform/src/test/java/platformstepdefinition/PF_HeaderAfterLogin.java
Labels: Code Review
